# Generated by Django 4.0 on 2022-07-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=50)),
                ('family_name', models.CharField(default=None, max_length=50)),
                ('given_name', models.CharField(default=None, max_length=50)),
                ('org', models.CharField(default=None, max_length=50)),
                ('email', models.CharField(default='example@domain.com', max_length=50)),
                ('work_phone', models.CharField(default=None, max_length=50)),
                ('mobile_phone', models.CharField(default=None, max_length=50)),
                ('fax', models.CharField(default=None, max_length=50)),
                ('direct_line', models.CharField(default=None, max_length=50)),
                ('website', models.CharField(default='www.domain.com', max_length=50)),
            ],
        ),
    ]
