# Generated by Django 4.0 on 2022-07-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_rename_employees_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='adr',
            field=models.CharField(default='First Floor,Pangaea Office Park,Lusaka Zambia', max_length=50),
        ),
    ]
