# Generated by Django 4.0 on 2022-07-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_employee_adr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='family_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fax',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
