# Generated by Django 4.0 on 2022-07-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_employee_family_name_alter_employee_fax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='direct_line',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile_phone',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
