# Generated by Django 4.0 on 2022-10-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_employee_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.CharField(default='example@pangaea.co.zm', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='org',
            field=models.CharField(default='PANGAEA SECURITIES LIMITED', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='website',
            field=models.CharField(default='www.pangaea.co.zm', max_length=50),
        ),
    ]
